#!/bin/sh

set -- `echo $DOCUMENT_URI | tr '/' ' '`
_TITLE="`cat title`"
ITEM_PATH=$DOCUMENT_ROOT/items/poem/items/$iid
link_path="$ITEM_PATH/link"

if test -f "$link_path"; then
	iid="`awk '{print $1}' $link_path`"
	link_g="`awk '{print $2}' $link_path`"
	link_f="`awk '{print $3}' $link_path`"
	ITEM_PATH=$DOCUMENT_ROOT/items/poem/items/$iid
fi

poem_path=$ITEM_PATH

touch $DOCUMENT_ROOT/tmp/notitle
ITEM_PATH="$poem_path/pt_PT.html"

new_item_path="$poem_path/$lang.html"
test ! -f $new_item_path || ITEM_PATH=$new_item_path

cat - > $DOCUMENT_ROOT/tmp/fun <<!
<div class='tac v f cf15 tsxl'>`counter_inc $poem_path/counter.txt`</div>
!

test -z "$HTTP_PARAM_g" || link_g="$HTTP_PARAM_g"
test -z "$HTTP_PARAM_f" || link_f="$HTTP_PARAM_f"

link_g=`grep -n "$link_g" $ITEM_PATH | head -n 1 | tr ':' ' ' | awk '{print $1}'`
link_f=`grep -n "$link_f" $ITEM_PATH | head -n 1 | tr ':' ' ' | awk '{print $1}'`
link_d=`math $link_f - $link_g`

may_head() {
	test $link_d -ge 1 && head -n $link_d || cat
}

cat - <<!
<object type="text/html" data="/poem/$iid/$lang.html?v=`date +%s`#$HTTP_PARAM_s" class="sf fg"></object>
!
